
set_property IOSTANDARD LVCMOS33 [get_ports clk_100k]
set_property PACKAGE_PIN T14 [get_ports clk_100k]
#io[0]
set_property IOSTANDARD LVCMOS33 [get_ports sclke]
set_property PACKAGE_PIN U12 [get_ports sclke]
#io[1]
set_property PACKAGE_PIN U13 [get_ports cse]
set_property IOSTANDARD LVCMOS33 [get_ports cse]
#io[2]
set_property PACKAGE_PIN V13 [get_ports mosie]
set_property IOSTANDARD LVCMOS33 [get_ports mosie]
#io[3]
set_property PACKAGE_PIN V15 [get_ports misoe]
set_property IOSTANDARD LVCMOS33 [get_ports misoe]
#io[4]
set_property PACKAGE_PIN T15 [get_ports rdre]
set_property IOSTANDARD LVCMOS33 [get_ports rdre]
#io[5]
set_property PACKAGE_PIN R16 [get_ports pulse]
set_property IOSTANDARD LVCMOS33 [get_ports pulse]
#io[6]

#set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
#set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
#set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]

set_false_path -from [get_clocks clk_fpga_0] -to [get_clocks clk_fpga_1]
set_false_path -from [get_clocks clk_fpga_0] -to [get_clocks clk_fpga_2]
set_false_path -from [get_clocks clk_fpga_1] -to [get_clocks clk_fpga_0]
set_false_path -from [get_clocks clk_fpga_1] -to [get_clocks clk_fpga_2]
set_false_path -from [get_clocks clk_fpga_2] -to [get_clocks clk_fpga_0]
set_false_path -from [get_clocks clk_fpga_2] -to [get_clocks clk_fpga_1]